//PRODUCTS
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const SYNC_PRODUCTS_START = "SYNC_PRODUCTS_START";
export const GET_TYPE_PRODUCT_SELECT = "GET_TYPE_PRODUCT_SELECT";
export const GET_ALL_COUNT_REVIEWS = "GET_ALL_COUNT_REVIEWS";
export const GET_ALL_COUNT_PRODUCTS = "GET_ALL_COUNT_PRODUCTS";
export const GET_ALL_PRODUCTS_DB = "GET_ALL_PRODUCTS_DB";
export const ADD_REVIEW = "ADD_REVIEW";
export const ADD_REVIEW_COLLECTIONS = "ADD_REVIEW_COLLECTIONS";
export const UPDATE_COUNT_REVIEW_PRODUCT = "UPDATE_COUNT_REVIEW_PRODUCT";
export const GET_ALL_PUBLISH_REVIEWS = "GET_ALL_PUBLISH_REVIEWS";
export const GET_ALL_UNPUBLISH_REVIEWS = "GET_ALL_UNPUBLISH_REVIEWS";
export const GET_COUNT_PRODUCTS_NO_REVIEWS = "GET_COUNT_PRODUCTS_NO_REVIEWS";
// export const DELETE_ALL_REVIEWS = "DELETE_ALL_REVIEWS";
export const PUBLISH_ALL_REVIEWS = "PUBLISH_ALL_REVIEWS";
export const UN_PUBLISH_ALL_REVIEWS = "UN_PUBLISH_ALL_REVIEWS";
export const GET_PRODUCTS_SEARCH = "GET_PRODUCTS_SEARCH";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_ALL_REVIEWS_BY_PRODUCT_IN_PAGE =
  "GET_ALL_REVIEWS_BY_PRODUCT_IN_PAGE";
export const DELETE_ONE_REVIEW = "DELETE_ONE_REVIEW";
export const GET_COUNT_REVIEW_BY_PRODUCT = "GET_COUNT_REVIEW_BY_PRODUCT";
export const SYNC_DATA = "SYNC_DATA";
export const GET_IMAGE_REVIEWS = "GET_IMAGE_REVIEWS";
export const GET_ALL_REVIEWS_BY_PRODUCT = "GET_ALL_REVIEWS_BY_PRODUCT";
export const GET_REVIEWS_EDIT = "GET_REVIEWS_EDIT";
export const EDIT_REVIEW = "EDIT_REVIEW";
export const GET_IMAGE_IN_REVIEW = "GET_IMAGE_IN_REVIEW";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const UN_PUBLISH_REVIEW_CHECKED = "UN_PUBLISH_REVIEW_CHECKED";
export const CHANGE_CHECKED_REVIEWS = "CHANGE_CHECKED_REVIEWS";
export const PUBLISH_REVIEW_CHECKED = "PUBLISH_REVIEW_CHECKED";
export const UN_FLAG_REVIEW_CHECKED = "UN_FLAG_REVIEW_CHECKED";
export const FLAG_REVIEW_CHECKED = "FLAG_REVIEW_CHECKED";
export const DELETE_REVIEWS_CHECKED = "DELETE_REVIEWS_CHECKED";
export const IMPORT_REVIEWS_EXCEL = "IMPORT_REVIEWS_EXCEL";
export const CHANGE_CHECKED_PRODUCTS = "CHANGE_CHECKED_PRODUCTS";
export const PUBLISH_REVIEW_PRODUCTS_CHECKED =
  "PUBLISH_REVIEW_PRODUCTS_CHECKED";
export const UN_PUBLISH_REVIEW_PRODUCTS_CHECKED =
  "UN_PUBLISH_REVIEW_PRODUCTS_CHECKED";
export const UN_FLAG_REVIEW_PRODUCTS_CHECKED =
  "UN_FLAG_REVIEW_PRODUCTS_CHECKED";
export const FLAG_REVIEW_PRODUCTS_CHECKED = "FLAG_REVIEW_PRODUCTS_CHECKED";
export const DELETE_REVIEW_PRODUCTS_CHECKED = "DELETE_REVIEW_PRODUCTS_CHECKED";
export const GET_COUNT_PRODUCT_IN_SHOPIFY = "GET_COUNT_PRODUCT_IN_SHOPIFY";
export const SYNC_PRODUCTS_SHOPIFY = "SYNC_PRODUCTS_SHOPIFY";
export const DELETE_IMAGE_MULTI_PRODUCTS = "DELETE_IMAGE_MULTI_PRODUCTS";
export const SYNC_COLLECTIONS = "SYNC_COLLECTIONS";
export const GET_VENDOR_PRODUCT = "GET_VENDOR_PRODUCT";
export const LOADING_DATA_TABLE = "LOADING_DATA_TABLE";
export const GET_COLLECTIONS_SELECT = "GET_COLLECTIONS_SELECT";
export const RESET_ARR_PRODUCTS_IMPORT = "RESET_ARR_PRODUCTS_IMPORT";
export const LOADING_THEME_DETAIL = "LOADING_THEME_DETAIL";
// export const UNSUBSCRIBE_PRODUCT = "UNSUBSCRIBE_PRODUCT";
export const GET_REVIEWS_EDIT_COLLECTION_TYPE =
  "GET_REVIEWS_EDIT_COLLECTION_TYPE";
export const CLEAR_REVIEWS_CHECKED = "CLEAR_REVIEWS_CHECKED";
export const CHANGE_IMAGE = "CHANGE_IMAGE";
export const RESET_IMAGE = "RESET_IMAGE";
//SETTINGS
export const GET_SETTINGS = "GET_SETTINGS";
export const SHOW_NOTIFICATION_DEMO = "SHOW_NOTIFICATION_DEMO";
export const HIDE_NOTIFICATION_DEMO = "HIDE_NOTIFICATION_DEMO";
export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const SAVE_ERROR = "SAVE_ERROR";
export const RELOAD_SETTINGS = "RELOAD_SETTINGS";

// IMPORT URL
export const SEARCH_REVIEWS_URL = "SEARCH_REVIEWS_URL";
export const RELOAD_IMPORT = "RELOAD_IMPORT";
export const RELOAD_REVIEWS = "RELOAD_REVIEWS";
export const SAVE_AND_LOAD_MORE = "SAVE_AND_LOAD_MORE";
export const SAVE_AND_LOAD_MORE_MULTI_PRODUCTS =
  "SAVE_AND_LOAD_MORE_MULTI_PRODUCTS";
export const SAVE_AND_LOAD_MORE_COLLECTIONS = "SAVE_AND_LOAD_MORE_COLLECTIONS";
export const SAVE_AND_LOAD_MORE_TYPE = "SAVE_AND_LOAD_MORE_TYPE";
export const PUSH_REVIEWS_URL = "PUSH_REVIEWS_URL";
// export const UPDATE_COUNT_MULTI_PRODUCTS = "UPDATE_COUNT_MULTI_PRODUCTS";
export const CLEAR_DATA_IMPORT = "CLEAR_DATA_IMPORT";
export const CHANGE_CHECKED_REVIEWS_IMPORT = "CHANGE_CHECKED_REVIEWS_IMPORT";
export const DELETE_CHECKED_REVIEWS_IMPORT = "DELETE_CHECKED_REVIEWS_IMPORT";
export const REPLACE_REVIEWS_IMPORT = "REPLACE_REVIEWS_IMPORT";
export const GET_ARR_PRODUCTS_IMPORT = "GET_ARR_PRODUCTS_IMPORT";
export const CHANGE_ARR_PRODUCTS_IMPORT = "CHANGE_ARR_PRODUCTS_IMPORT";
export const RESET_ARR_PRODUCT_IMPORT = "RESET_ARR_PRODUCT_IMPORT";
export const ERROR_IMPORT_URL = "ERROR_IMPORT_URL";
export const RELOAD_IMPORT_WHEN_SAVE = "RELOAD_IMPORT_WHEN_SAVE";

//alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//REVIEWS
export const GET_REVIEWS_SEARCH = "GET_REVIEWS_SEARCH";
export const REVIEWS_ERROR = "REVIEWS_ERROR";
export const GET_IMAGE_REVIEWS_REVIEW_PAGE = "GET_IMAGE_REVIEWS_REVIEW_PAGE";
export const LOADING_DATA_TABLE_REVIEW = "LOADING_DATA_TABLE_REVIEW";
export const GET_ALL_COUNT_REVIEWS_REVIEW_PAGE =
  "GET_ALL_COUNT_REVIEWS_REVIEW_PAGE";
export const RELOAD_REVIEWS_REVIEW_PAGE = "RELOAD_REVIEWS_REVIEW_PAGE";
export const GET_CONNECT_COLLECTION_REVIEWS = "GET_CONNECT_COLLECTION_REVIEWS";
export const GET_CONNECT_PRODUCT_TYPE_REVIEWS =
  "GET_CONNECT_PRODUCT_TYPE_REVIEWS";
export const GET_CONNECT_PRODUCT_REVIEWS = "GET_CONNECT_PRODUCT_REVIEWS";
export const GET_REQUEST_SEARCH = "GET_REQUEST_SEARCH";

//STATISTICAL
export const QUERY_ERROR_STATISTICAL = "QUERY_ERROR_STATISTICAL";
export const GET_ALL_COUNT_REVIEWS_STATISTICAL =
  "GET_ALL_COUNT_REVIEWS_STATISTICAL";
export const GET_ALL_PUBLISH_REVIEWS_STATISTICAL =
  "GET_ALL_PUBLISH_REVIEWS_STATISTICAL";
export const GET_ALL_UNPUBLISH_REVIEWS_STATISTICAL =
  "GET_ALL_UNPUBLISH_REVIEWS_STATISTICAL";
export const GET_COUNT_PRODUCTS_NO_REVIEWS_STATISTICAL =
  "GET_COUNT_PRODUCTS_NO_REVIEWS_STATISTICAL";
export const GET_COUNT_PRODUCT_IN_SHOPIFY_STATISTICAL =
  "GET_COUNT_PRODUCT_IN_SHOPIFY_STATISTICAL";
export const GET_TYPE_PRODUCT_STATISTICAL = "GET_TYPE_PRODUCT_STATISTICAL";
export const GET_COLLECTIONS_STATISTICAL = "GET_COLLECTIONS_STATISTICAL";
export const GET_RATING_STATISTICAL = "GET_RATING_STATISTICAL";
export const GET_REVIEWS_PLACE_STATISTICAL = "GET_REVIEWS_PLACE_STATISTICAL";
//COLLECTIONS
export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const CHANGE_CHECKED_COLLECTION = "CHANGE_CHECKED_COLLECTION";
export const CHANGE_CHECKED_COLLECTION_IMPORT =
  "CHANGE_CHECKED_COLLECTION_IMPORT";
export const COLLECTION_ERROR = "COLLECTION_ERROR";
export const GET_ARR_COLLECTIONS_IMPORT = "GET_ARR_COLLECTIONS_IMPORT";
export const LOADING_DATA_TABLE_COLLECTION = "LOADING_DATA_TABLE_COLLECTION";
export const RELOAD_COLLECTION = "RELOAD_COLLECTION";
export const CLEAR_DATA_IMPORT_COLLECTION = "CLEAR_DATA_IMPORT_COLLECTION";
export const GET_COUNT_COLLECTIONS = "GET_COUNT_COLLECTIONS";
//PRODUCT_TYPES
export const GET_TYPE_PRODUCT = "GET_TYPE_PRODUCT";
export const GET_COUNT_TYPE_PRODUCT = "GET_COUNT_TYPE_PRODUCT";
export const CHANGE_CHECKED_PRODUCT_TYPES = "CHANGE_CHECKED_PRODUCT_TYPES";
export const PRODUCT_TYPES_ERROR = "PRODUCT_TYPES_ERROR";
export const LOADING_DATA_TABLE_PRODUCT_TYPES =
  "LOADING_DATA_TABLE_PRODUCT_TYPES";
export const RELOAD_PRODUCT_TYPES = "RELOAD_PRODUCT_TYPES";
export const CHANGE_CHECKED_PRODUCT_TYPES_IMPORT =
  "CHANGE_CHECKED_PRODUCT_TYPES_IMPORT";
export const GET_ARR_PRODUCT_TYPES_IMPORT = "GET_ARR_PRODUCT_TYPES_IMPORT";
export const CLEAR_DATA_IMPORT_PRODUCT_TYPE = "CLEAR_DATA_IMPORT_PRODUCT_TYPE";
